[all_server]
server1 ansible_host=192.168.31.226
server2 ansible_host=192.168.31.218
server3 ansible_host=192.168.31.215

[monitoring_node]
server1 ansible_host=192.168.31.226

[monitoring_agents]
server2 ansible_host=192.168.31.218
server3 ansible_host=192.168.31.215

[all:vars]
ansible_user=meowzonn
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
